let s = 2000000;
let years = 5;
let month = years * 12;
let p = 0.1;
let perepl = 0;
let monthRate = p / month;
let topPart = +(s * monthRate).toFixed(2);
let bottomPart = +(1 - (1 / Math.pow(monthRate + 1, month))).toFixed(2);
perepl = +(topPart / bottomPart).toFixed(2);
console.log (perepl * month);